TdU高度化: pytorch版Faster R-CNNのサーバ化
keio-smilab22/frcnn-fine-tuning pull request #1
Opened 2022-04-11 07:10 UTC by kosec-kajiyama

2022-04-11 10:11 UTC, kosec-matsumura requested changes
修正をお願いします。

2022-04-11 10:11 UTC, kosec-matsumura commented on src/frcnn.py
> +        一発うちをっこうする
`一発打ち`は左記の表記でお願いします。（打ちが漢字）

2022-04-14 06:08 UTC, kosec-kajiyama commented on scripts/predict_oneshot.sh
> +    --config $config \
modelやoutputのディレクトリ等の設定のために必要です

2022-04-14 10:03 UTC, kosec-matsumura commented on config/server_config.json
> +}
`config/config.json`に改行コードが追加されていません。

2022-04-14 10:03 UTC, kosec-matsumura commented on scripts/predict_oneshot.sh
> +    --config $config \
承知しました。対応不要です。

2022-04-14 10:14 UTC, kosec-matsumura requested changes
修正をお願いします。

2022-04-14 10:14 UTC, kosec-matsumura commented on src/main.py
> +            if args.server_config is not None:
パラメータが設定されていないときのエラーかと思いますが、そもそも、設定されていないのであれば、NoneではなくAttributeErrorが返されるのではないでしょうか。

2022-04-14 10:45 UTC, kosec-kajiyama commented on src/main.py
> +            if args.server_config is not None:
Noneになるので修正しない

2022-04-15 07:22 UTC, kosec-matsumura approved these changes
確認しました。OKです。

2022-04-15 07:24 UTC, merged